# Generated by Django 4.2.16 on 2024-11-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('tutor', 'Tutor')], default='student', max_length=10),
        ),
    ]
