# Generated by Django 5.1.2 on 2024-11-23 18:35

import django.utils.timezone
import tutorials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_course_admin_student_tutor_session_studentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('JavaScript', 'JavaScript'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust')], help_text='Select a programming language', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('JavaScript', 'JavaScript'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust')], help_text='Select a programming language', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=tutorials.models.default_end_time),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='expertise',
        ),
        migrations.AddField(
            model_name='tutor',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='Select programming languages the tutor can teach', related_name='tutors', to='tutorials.programminglanguage'),
        ),
    ]
