# Generated by Django 5.1.2 on 2024-11-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_user_role'),
        ('tutorials', '0004_remove_session_course_session_programming_language_and_more'),
    ]

    operations = [
    ]
