# Generated by Django 5.1.2 on 2024-11-27 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_remove_tutor_hourly_rate_student_previous_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_level',
        ),
        migrations.AddField(
            model_name='session',
            name='is_availble',
            field=models.BooleanField(default=True, help_text='Indicates if the session is available for registration'),
        ),
        migrations.CreateModel(
            name='RequestedStudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Indicates if the session request is approved')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tutorials.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_sessions', to='tutorials.student')),
            ],
        ),
    ]
