# Generated by Django 5.1.2 on 2024-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_alter_session_end_day_alter_session_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', help_text='Select a Level', max_length=20),
        ),
    ]
