# Generated by Django 5.1.2 on 2024-11-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_programminglanguage_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
