# Generated by Django 4.2.16 on 2024-11-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_remove_programminglanguage_level_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TUTOR', 'Tutor')], default='ADMIN', max_length=10),
        ),
    ]
