# Generated by Django 4.2.16 on 2024-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly')], default='Weekly', max_length=20),
        ),
    ]
