# Generated by Django 4.2.16 on 2024-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_alter_session_frequency'),
        ('tutorials', '0016_alter_session_frequency_invoice'),
    ]

    operations = [
    ]
