# Generated by Django 5.1.2 on 2024-12-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_merge_20241206_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsession',
            unique_together=set(),
        ),
    ]
