# Generated by Django 5.1.2 on 2024-12-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0018_alter_studentsession_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestedstudentsession',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Requested Student Session', 'verbose_name_plural': 'Requested Student Sessions'},
        ),
        migrations.AlterModelOptions(
            name='studentsession',
            options={'verbose_name': 'Student Session', 'verbose_name_plural': 'Student Sessions'},
        ),
        migrations.AlterUniqueTogether(
            name='requestedstudentsession',
            unique_together={('student', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsession',
            unique_together={('student', 'tutor_session')},
        ),
    ]
