# Generated by Django 5.1.2 on 2024-12-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0018_remove_invoice_requested_session_invoice_session_and_more'),
        ('tutorials', '0019_alter_requestedstudentsession_options_and_more'),
    ]

    operations = [
    ]
