# Generated by Django 5.1.2 on 2024-12-10 21:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_merge_20241210_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='status',
            field=models.CharField(choices=[('Send Invoice', 'Send Invoice'), ('Payment Pending', 'Payment Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Send Invoice', max_length=20),
        ),
    ]
