# Generated by Django 5.1.2 on 2024-12-12 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0022_alter_tutorsession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.PositiveIntegerField(help_text='Enter the year (e.g., 2024)', validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
