# Generated by Django 4.2.16 on 2024-12-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0023_alter_session_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tutorials.studentsession'),
        ),
    ]
