# Generated by Django 5.1.2 on 2024-12-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0023_alter_session_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tutorials.studentsession'),
        ),
    ]
